name: Build base Docker images

on: [push]

env:
  IMAGE_NAME: base
  IMAGE_PLATFORM: linux/amd64
  IMAGE_DOCKERFILE: Dockerfile
  EXTRA_BUILD_ARGS: --pull

jobs:
  build:
    runs-on: [self-hosted, heavy-build]
    strategy:
      matrix:
        include:
          - IMAGE_TAG: 22.04
          - IMAGE_TAG: 24.04
    steps:
      - uses: actions/checkout@v4
      - name: docker build
        run: |
          echo "Building Docker image:"
          echo "    full name        : ${{ vars.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.IMAGE_TAG }}"
          echo "    platform         : ${{ env.IMAGE_PLATFORM }}"
          echo "    workdir          : ${{ env.IMAGE_NAME }}/${{ matrix.IMAGE_TAG }}"
          echo "    dockerfile       : ${{ env.IMAGE_DOCKERFILE }}"
          echo "    extra build args : ${{ env.EXTRA_BUILD_ARGS }}"

          cd ${{ env.IMAGE_NAME }}/${{ matrix.IMAGE_TAG }}
          docker buildx build --no-cache \
                              --platform ${{ env.IMAGE_PLATFORM }} \
                              -f ${{ env.IMAGE_DOCKERFILE }} \
                              -t ${{ vars.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.IMAGE_TAG }} \
                              ${{ env.EXTRA_BUILD_ARGS }} \
                              .
      - name: docker save
        run: |
          docker save -o ${{ env.IMAGE_NAME }}-${{ matrix.IMAGE_TAG }} ${{ vars.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.IMAGE_TAG }}
          pwd
          ls -al
          echo ${GITHUB_WORKSPACE}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.IMAGE_NAME }}-${{ matrix.IMAGE_TAG }}
          path: ${{ env.IMAGE_NAME }}-${{ matrix.IMAGE_TAG }}
      - name: cleanup
        run: rm ${{ env.IMAGE_NAME }}-${{ matrix.IMAGE_TAG }}
