name: Build Docker images with doxygen

on: [push]

env:
  IMAGE_NAME: doxygen

jobs:
  build-doxygen:
    runs-on: [self-hosted, heavy-build]
    strategy:
      fail-fast: false
      matrix:
        IMAGE_TAG: [22.04, 24.04]
    steps:
      - uses: actions/checkout@v4
      - name: docker build
        uses: ./.github/actions/docker-build
        with:
          image: ${{ env.IMAGE_NAME }}
          tag: ${{ matrix.IMAGE_TAG }}
          workdir: ${{ env.IMAGE_NAME }}/${{ matrix.IMAGE_TAG }}
          extraBuildArgs: --pull

  deploy-doxygen:
    runs-on: [self-hosted, heavy-build]
    if: github.ref_name == 'main'
    needs: build
    strategy:
      matrix:
        IMAGE_TAG: [22.04, 24.04]
    steps:
      - name: docker push
        uses: ./.github/actions/docker-push
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image: ${{ env.IMAGE_NAME }}
          tag: ${{ matrix.IMAGE_TAG }}
